project:
  type: website
  output-dir: docs

website:
  title: "Bobblite"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Bobblite
      - icon: linkedin
        href: https://www.linkedin.com/in/ming-yang-lee-0859a3143/
format:
  html:
    theme: simplex
    css: styles.css



