project:
  type: website
  output-dir: docs  

website:
  title: "Bobblite"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Bobblite
      - icon: linkedin
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css



